# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"_\n\x0fRequestVoteArgs\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\x03\x12\x13\n\x0blastLogTerm\x18\x03 \x01(\x03\x12\x14\n\x0clastLogIndex\x18\x04 \x01(\x03\"M\n\x10RequestVoteReply\x12\x13\n\x0bvoteGranted\x18\x01 \x01(\x08\x12\x0c\n\x04term\x18\x02 \x01(\x03\x12\x16\n\x0eremainingLease\x18\x03 \x01(\x02\"\xac\x01\n\x11\x41ppendEntriesArgs\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x10\n\x08leaderId\x18\x02 \x01(\x03\x12\x13\n\x0bprevLogTerm\x18\x03 \x01(\x03\x12\x14\n\x0cprevLogIndex\x18\x04 \x01(\x03\x12\x15\n\rleaseInterval\x18\x05 \x01(\x03\x12\x1f\n\x07\x65ntries\x18\x06 \x03(\x0b\x32\x0e.raft.LogEntry\x12\x14\n\x0cleaderCommit\x18\x07 \x01(\x03\"3\n\x12\x41ppendEntriesReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0c\n\x04term\x18\x02 \x01(\x03\"&\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"\"\n\x0fServeClientArgs\x12\x0f\n\x07Request\x18\x01 \x01(\t\"C\n\x10ServeClientReply\x12\x0c\n\x04\x44\x61ta\x18\x01 \x01(\t\x12\x10\n\x08LeaderID\x18\x02 \x01(\x05\x12\x0f\n\x07Success\x18\x03 \x01(\x08\x32\xc8\x01\n\x04Raft\x12<\n\x0bRequestVote\x12\x15.raft.RequestVoteArgs\x1a\x16.raft.RequestVoteReply\x12\x42\n\rAppendEntries\x12\x17.raft.AppendEntriesArgs\x1a\x18.raft.AppendEntriesReply\x12>\n\x0bServeClient\x12\x15.raft.ServeClientArgs\x1a\x16.raft.ServeClientReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTVOTEARGS']._serialized_start=20
  _globals['_REQUESTVOTEARGS']._serialized_end=115
  _globals['_REQUESTVOTEREPLY']._serialized_start=117
  _globals['_REQUESTVOTEREPLY']._serialized_end=194
  _globals['_APPENDENTRIESARGS']._serialized_start=197
  _globals['_APPENDENTRIESARGS']._serialized_end=369
  _globals['_APPENDENTRIESREPLY']._serialized_start=371
  _globals['_APPENDENTRIESREPLY']._serialized_end=422
  _globals['_LOGENTRY']._serialized_start=424
  _globals['_LOGENTRY']._serialized_end=462
  _globals['_SERVECLIENTARGS']._serialized_start=464
  _globals['_SERVECLIENTARGS']._serialized_end=498
  _globals['_SERVECLIENTREPLY']._serialized_start=500
  _globals['_SERVECLIENTREPLY']._serialized_end=567
  _globals['_RAFT']._serialized_start=570
  _globals['_RAFT']._serialized_end=770
# @@protoc_insertion_point(module_scope)
